# Parameters for Dilated Network prediction on VOC2012 dataset.

# The batch size on prediction..
batch_size: 4
# The height of resized image for prediciton.
test_resized_height: 512
# The width of resized image for prediction.
test_resized_width: 1024
# The directory path to save outputs.
save_dir: "./outputs"
# which model to use from frontend, dilation7, dilation8, and dilation10
mode: "dilation7"
# The number of classes to use.
num_classes: 20
# The number of workers for tf.data.Dataset.map().
num_parallel_calls: 10
# The parameter for tf.data.Dataset.prefetch().
prefetch_buffer_size: 10
# The prefix path to the ckpt files to load from.
ckpt_path: "tmp/2018-08-04\ 23:55:10.251645/ckpts/00000014"
# Path to the VOC2012 tfrecord data directory.
# The data should be created by sss.data.tfrecord.write_tfrecord.
tfdata_dir: "/home/ubuntu/workspace/local_data/voc/VOCdevkit/VOC2012/tfrecord"
